export const skills = [
    {technology:'Python', profiency:'100', experience: '4+ years', type: ['Data Science', 'Back-end', 'Data Engineering', 'Machine Learning', 'Deep Learning', 'Data Analysis']},
    {technology:'Javascript', profiency:'100', experience: '3+ years', type: ['Front-end']},
    {technology:'SQL', profiency:'100', experience: '3+ years', type: ['Database', 'Data Science', 'Back-end', 'Data Engineering']},
    {technology:'Java', profiency:'75', experience: '2+ years', type: ['Data Science', 'Back-end']},
    {technology:'HTML', profiency:'75', experience: '4+ years', type: ['Front-end']},
    {technology:'CSS', profiency:'75', experience: '4+ years', type: ['Front-end']},
    {technology:'Pandas', profiency:'100', experience: '3+ years', type: ['Data Science']},
    {technology:'Scikit-Learn', profiency:'100', experience: '2+ years', type: ['Data Science', 'Machine Learning']},
    {technology:'Can Code From Scratch', profiency:'100', experience: '2+ years', type: ['Machine Learning']},
    {technology:'PyTorch', profiency:'75', experience: '2+ years', type: ['Data Science', 'Deep Learning']},
    {technology:'Svelte', profiency:'50', experience: 'less than 1 year', type: ['Front-end', 'Back-end']},
    {technology:'React', profiency:'75', experience: '2+ years', type: ['Front-end']},
    {technology:'PostgreSQL', profiency:'75', experience: '1+ years', type: ['Database', 'Back-end']},
    {technology:'SQL Server', profiency:'75', experience: '3+ years', type: ['Database', 'Back-end']},
    {technology:'REST API', profiency:'75', experience: '1+ years',type: ['Front-end', 'Back-end']},
    {technology:'AWS', profiency:'50', experience: 'less than 1 year',type: ['Cloud', 'Data Engineering']},
    {technology:'Apache Spark', profiency:'50', experience: 'less than 1 year',type: ['Data Engineering']},
    {technology:'EC2', profiency:'50', experience: 'less than 1 year',type: ['Cloud']},
    {technology:'Plotly', profiency:'100', experience: '2+ years', type: ['Data Science','Data Analysis']},
    {technology:'Matplotlib', profiency:'100', experience: '2+ years', type: ['Data Science','Data Analysis']},
    {technology:'Tableau', profiency:'75', experience: 'less than 1 year', type: ['Data Analysis']},
    {technology:'Excel', profiency:'100', experience: '3+ years', type: ['Data Analysis']},
    {technology:'Jupyter Notebook', profiency:'100', experience: '4+ years', type: ['Data Analysis']},
    
    ];